export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";

export const FETCH_SEARCHED_MOVIES = "FETCH_SEARCHED_MOVIES";
export const FETCH_SORTED_MOVIES = "FETCH_SORTED_MOVIES";
export const CLEAR_SEARCHED = "CLEAR_SEARCHED";

export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const INIT_MOVIE_DETAILS = "INIT_MOVIE_DETAILS";
export const INIT_FETCH_MOVIES = "INIT_FETCH_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
